In [16]:
import numpy as np 
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a,b)
print(type(a))
print(type(b))

[1 2 3 4 5] [ 6  7  8  9 10]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
print(a+b)
print(a*b)
print(a-b)

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[-5 -5 -5 -5 -5]


In [33]:
n2 = np.array([[1,2],[2,4],[1,4]])
print(n2)

[[1 2]
 [2 4]
 [1 4]]


In [35]:
print(n2.shape[1])# no. of rows and column
print(n2.ndim)#no. of dimension
print(n2.dtype)#data type of the element



2
2
int32


In [20]:
np.arange(1,100,5)# for range 

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [25]:
a = np.random.randint(1,10,size=(2,3))
print(a)


[[1 4 8]
 [7 5 5]]


In [43]:
x = np.array([[1,2,3],[2,4,3],[1,4,3]])
y = np.array([[1,2,3],[2,4,3],[1,4,3]])
print(x)
print(y)

[[1 2 3]
 [2 4 3]
 [1 4 3]]
[[1 2 3]
 [2 4 3]
 [1 4 3]]


In [44]:
print(x+y)
print(x*y) # multiple
print(x@y)

[[2 4 6]
 [4 8 6]
 [2 8 6]]
[[ 1  4  9]
 [ 4 16  9]
 [ 1 16  9]]
[[ 8 22 18]
 [13 32 27]
 [12 30 24]]


In [45]:
x.mean(axis = 1)

array([2.        , 3.        , 2.66666667])

In [46]:
x.mean()

2.5555555555555554

In [47]:
x.prod()# product

1728

In [48]:
print(x.min())

1


In [51]:
print(x.min(axis = 1))# minimum row value

[1 2 1]


In [53]:
print(x.min(axis = 0))#minimum column value

[1 2 3]


In [54]:
print(x.sum())
print(x.std())
print(x.var())

23
1.0657403385139377
1.1358024691358024


In [55]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,50))# 50%
print(np.percentile(a,25))# 25% or 1/4
print(np.percentile(a,75))#3 75% or 3/4

5.0
3.0
7.0


In [57]:
print(np.unique(x))# repeated value get removed

[1 2 3 4]


In [59]:
# reshape the array
a = np.random.randint(11,100,(4,4))
print(a)
print('2X8')
print(a.reshape(2,8))
print('2X4')
print(a.reshape(2,2,4))



[[25 94 25 79]
 [83 92 47 23]
 [78 63 49 84]
 [87 16 50 76]]
2X8
[[25 94 25 79 83 92 47 23]
 [78 63 49 84 87 16 50 76]]
2X4
[[[25 94 25 79]
  [83 92 47 23]]

 [[78 63 49 84]
  [87 16 50 76]]]
