In [57]:
import numpy as np


- crate 
- basic operation 
- math operation 
- indexing and slicing 
- boolean filter 

In [58]:
a = np.array ([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a,b)

[1 2 3 4 5] [ 6  7  8  9 10]


In [59]:
print(a+b)
print(a-b)
print(a*b)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]


In [60]:
a = np.array(([1,2,3],[2,3,4]))
print(a)
a.shape


[[1 2 3]
 [2 3 4]]


(2, 3)

In [61]:
a = np.random.randint(1,10,size=(5,5))
print(a)


[[9 7 4 9 4]
 [1 4 7 5 6]
 [9 3 8 5 9]
 [8 6 9 9 2]
 [8 2 8 6 9]]


In [62]:
a = np.random.rand(3,3)
print(a)


[[0.0720576  0.02413862 0.5854819 ]
 [0.16593299 0.03727535 0.65182441]
 [0.3298893  0.41157662 0.72100338]]


In [80]:
x = np.array([[1,2,3],[2,4,3]])
y = np.array([[1,2,3],[2,4,3]])
print(x)
print(y)
print(x+y)
print(x*y)
print(x-y)
print(x/y)

[[1 2 3]
 [2 4 3]]
[[1 2 3]
 [2 4 3]]
[[2 4 6]
 [4 8 6]]
[[ 1  4  9]
 [ 4 16  9]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [64]:
x.mean()

2.5555555555555554

In [65]:
a = np.arange(1,100,5)
a

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [66]:
# start , stop ,number_item
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

array attributes 
- shape
- dtype 
- ndim 
- size 

basic operation 
- sum 
- mean 
- std 
- max 
- min 
- reshape 
- transpose 
- flatten

In [67]:
x = np.random.rand(3,3)
x.dtype

dtype('float64')

In [68]:
b = np.random.randint(1,5, (3,3))
b.ndim

2

In [69]:
print(b.sum(axis = 1))

[6 9 5]


In [70]:
x = np.random.randint(1,10,(5,4)) # 5X5 matrix
x 

array([[2, 4, 9, 3],
       [3, 1, 4, 6],
       [6, 8, 1, 1],
       [8, 5, 2, 9],
       [2, 3, 3, 9]])

In [71]:
x.transpose()

array([[2, 3, 6, 8, 2],
       [4, 1, 8, 5, 3],
       [9, 4, 1, 2, 3],
       [3, 6, 1, 9, 9]])

In [72]:
x.flatten()

array([2, 4, 9, 3, 3, 1, 4, 6, 6, 8, 1, 1, 8, 5, 2, 9, 2, 3, 3, 9])

In [75]:
x.reshape(2,10)

array([[2, 4, 9, 3, 3, 1, 4, 6, 6, 8],
       [1, 1, 8, 5, 2, 9, 2, 3, 3, 9]])

In [82]:
print(a-10)
print(a/10)
print(a*10)
print(a+10)

[-9 -4  1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86]
[0.1 0.6 1.1 1.6 2.1 2.6 3.1 3.6 4.1 4.6 5.1 5.6 6.1 6.6 7.1 7.6 8.1 8.6
 9.1 9.6]
[ 10  60 110 160 210 260 310 360 410 460 510 560 610 660 710 760 810 860
 910 960]
[ 11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86  91  96
 101 106]


In [83]:
x = np.random.randint(1,10,(5,5)) # 5X5 matrix
print(x)

[[6 5 9 5 3]
 [1 8 2 8 9]
 [3 7 6 1 9]
 [6 5 3 7 8]
 [9 7 4 9 9]]


In [84]:
print(x[1:3])

[[1 8 2 8 9]
 [3 7 6 1 9]]


In [85]:
print(x[:,0])


[6 1 3 6 9]


In [86]:
print(x[:,:2])


[[6 5]
 [1 8]
 [3 7]
 [6 5]
 [9 7]]


In [87]:

print(x[1:-1,1:-1])

[[8 2 8]
 [7 6 1]
 [5 3 7]]


In [88]:
print(x[:,:-1])

[[6 5 9 5]
 [1 8 2 8]
 [3 7 6 1]
 [6 5 3 7]
 [9 7 4 9]]


In [94]:
print(x[1:-1,1:-1])

[[8 2 8]
 [7 6 1]
 [5 3 7]]
