In [1]:
import numpy as np


- crate 
- basic operation 
- math operation 
- indexing and slicing 
- boolean filter 

In [2]:
a = np.array ([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a,b)

[1 2 3 4 5] [ 6  7  8  9 10]


In [3]:
print(a+b)
print(a-b)
print(a*b)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]


In [4]:
a = np.array(([1,2,3],[2,3,4]))
print(a)
a.shape


[[1 2 3]
 [2 3 4]]


(2, 3)

In [5]:
a = np.random.randint(1,10,size=(5,5))
print(a)


[[9 3 1 4 1]
 [6 3 1 4 6]
 [4 6 9 1 2]
 [3 1 2 5 3]
 [3 1 3 3 9]]


In [6]:
a = np.random.rand(3,3)
print(a)


[[0.49836104 0.71017717 0.24533491]
 [0.60299576 0.03935698 0.6508641 ]
 [0.09875239 0.23787115 0.93840798]]


In [7]:
x = np.array([[1,2,3],[2,4,3]])
y = np.array([[1,2,3],[2,4,3]])
print(x)
print(y)
print(x+y)
print(x*y)
print(x-y)
print(x/y)

[[1 2 3]
 [2 4 3]]
[[1 2 3]
 [2 4 3]]
[[2 4 6]
 [4 8 6]]
[[ 1  4  9]
 [ 4 16  9]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
x.mean()

2.5

In [9]:
a = np.arange(1,100,5)
a

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [10]:
# start , stop ,number_item
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

array attributes 
- shape
- dtype 
- ndim 
- size 

basic operation 
- sum 
- mean 
- std 
- max 
- min 
- reshape 
- transpose 
- flatten

In [11]:
x = np.random.rand(3,3)
x.dtype

dtype('float64')

In [12]:
b = np.random.randint(1,5, (3,3))
b.ndim

2

In [13]:
print(b.sum(axis = 1))

[ 5  9 10]


In [14]:
x = np.random.randint(1,10,(5,4)) # 5X5 matrix
x 

array([[2, 2, 9, 5],
       [1, 9, 9, 7],
       [5, 1, 9, 3],
       [2, 2, 9, 4],
       [7, 7, 1, 6]])

In [15]:
x.transpose()

array([[2, 1, 5, 2, 7],
       [2, 9, 1, 2, 7],
       [9, 9, 9, 9, 1],
       [5, 7, 3, 4, 6]])

In [16]:
x.flatten()

array([2, 2, 9, 5, 1, 9, 9, 7, 5, 1, 9, 3, 2, 2, 9, 4, 7, 7, 1, 6])

In [17]:
x.reshape(2,10)

array([[2, 2, 9, 5, 1, 9, 9, 7, 5, 1],
       [9, 3, 2, 2, 9, 4, 7, 7, 1, 6]])

In [18]:
print(a-10)
print(a/10)
print(a*10)
print(a+10)

[-9 -4  1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86]
[0.1 0.6 1.1 1.6 2.1 2.6 3.1 3.6 4.1 4.6 5.1 5.6 6.1 6.6 7.1 7.6 8.1 8.6
 9.1 9.6]
[ 10  60 110 160 210 260 310 360 410 460 510 560 610 660 710 760 810 860
 910 960]
[ 11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86  91  96
 101 106]


In [19]:
x = np.random.randint(1,10,(5,5)) # 5X5 matrix
print(x)

[[6 1 5 2 1]
 [3 4 5 3 9]
 [2 7 4 1 2]
 [2 9 1 3 2]
 [8 8 8 4 1]]


In [20]:
print(x[1:3])

[[3 4 5 3 9]
 [2 7 4 1 2]]


In [21]:
print(x[:,0])


[6 3 2 2 8]


In [22]:
print(x[:,:2])


[[6 1]
 [3 4]
 [2 7]
 [2 9]
 [8 8]]


In [23]:

print(x[1:-1,1:-1])

[[4 5 3]
 [7 4 1]
 [9 1 3]]


In [24]:
print(x[:,:-1])

[[6 1 5 2]
 [3 4 5 3]
 [2 7 4 1]
 [2 9 1 3]
 [8 8 8 4]]


In [25]:
print(x[1:-1,1:-1])

[[4 5 3]
 [7 4 1]
 [9 1 3]]


In [26]:
x = np.arange(1,101).reshape(25,4)
x

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [27]:
x >= 50 # boolean filter

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
x[x>=50]

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [29]:
x[(x>=25)& (x<=75)]

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75])