In [11]:
import numpy as np 

##for statistical value in numpy

In [12]:
import numpy as np

In [13]:
a = np.array([1,2,3])

In [14]:
print(a)

[1 2 3]


In [15]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


## Basic operataion of array

In [16]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


### creating more then 2d array

In [17]:
a2 = np.array([[1,2,3,],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [20]:
print(a2.shape) 

(2, 3)


In [22]:
print(a2.ndim)# ndim(number of dimension)

2


In [23]:
np.arange(1,11)




array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
array = np.random.randint(1,11,size=(3,4))
print(array)

[[ 3  4  6  6]
 [10  7  8  6]
 [ 8  7  3  3]]


In [30]:
x= np.array([[4,5,3,],
            [3,4,6,],
            [3,5,3,]])
y= np.array([[4,5,3,],
            [3,4,6,],
            [3,5,3,]])
print(x)
print(y)


[[4 5 3]
 [3 4 6]
 [3 5 3]]
[[4 5 3]
 [3 4 6]
 [3 5 3]]


In [32]:
print(x@y) # matrix multiplication

[[40 55 51]
 [42 61 51]
 [36 50 48]]


In [36]:
np.dot(x,y)

array([[40, 55, 51],
       [42, 61, 51],
       [36, 50, 48]])

In [35]:
x.prod()

194400

In [37]:
x.mean()

4.0